"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.APP_TEAM_NAME = void 0;
exports.APP_TEAM_NAME = {
    ger: 'Germany',
    fra: 'France',
    esp: 'Spain',
    eng: 'England',
    por: 'Portugal',
    ned: 'Netherlands',
    bel: 'Belgium',
    ita: 'Italy',
    aut: 'Austria',
    sui: 'Switzerland',
    hun: 'Hungary',
    sco: 'Scotland',
    cze: 'Czech Republic',
    tur: 'Turkey',
    srb: 'Serbia',
    alb: 'Albania',
    bra: 'Brazil',
    arg: 'Argentina',
    col: 'Colombia',
    uru: 'Uruguay',
    ecu: 'Ecuador',
    ven: 'Venezuela',
    usa: 'United States',
    mex: 'Mexico',
    can: 'Canada',
    pan: 'Panama',
    crc: 'Costa Rica',
    jam: 'Jamaica',
    mar: 'Morocco',
    sen: 'Senegal',
    egy: 'Egypt',
    nga: 'Nigeria',
    cmr: 'Cameroon',
    civ: "Cote d'Ivoire",
    drc: 'DR Congo',
    gnb: 'Guinea-Bissau',
    tun: 'Tunisia',
    jpn: 'Japan',
    kor: 'South Korea',
    aus: 'Australia',
    irn: 'Iran',
    sau: 'Saudi Arabia',
    qat: 'Qatar',
    uzb: 'Uzbekistan',
    jor: 'Jordan',
    irq: 'Iraq',
    nzl: 'New Zealand',
    // Additional WC 2026 teams
    bih: 'Bosnia and Herzegovina',
    hai: 'Haiti',
    zaf: 'South Africa',
    par: 'Paraguay',
    cuw: 'Curacao',
    swe: 'Sweden',
    cpv: 'Cape Verde',
    nor: 'Norway',
    alg: 'Algeria',
    cro: 'Croatia',
    gha: 'Ghana',
};
